export const DESIGNREFRESH =  'DESIGNREFRESH';
export const DESIGNLISTUPDATE =  'DESIGNLISTUPDATE';
export const PUSHDESIGN =  'PUSHDESIGN';
export const GETONEDESIGN =  'GETONEDESIGN';
export const SETPHOTO =  'SETPHOTO';
export const REFRESHTAGS =  'REFRESHTAGS';